[package]
name = "brewfatherlog"
description = "Log temperatures from grainfather fermenters to brewfather"
version = "0.0.0-pre"
authors = ["Diogo Sousa <diogogsousa@gmail.com>"]

edition = "2021"

homepage = "https://github.com/orium/brewfatherlog"
repository = "https://github.com/orium/brewfatherlog"
readme = "README.md"

keywords = [
    "brewing", "fermentation", "grainfather", "brewfather", "logging"
]

license = "MPL-2.0"

# What to include when packaging.
include = [
    "/src/**/*.rs",
    "/Cargo.toml",
    "/Cargo.lock",
    "/LICENSE.md",
    "/README.md",
    "/release-notes.md",
]

[dependencies]

[features]
fatal-warnings = []

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
correctness = "deny"

enum-variant-names = "allow"
if-not-else = "allow"
inline-always = "allow"
match-bool = "allow"
missing-errors-doc = "allow"
module-name-repetitions = "allow"
needless-raw-string-hashes = "allow"
new-without-default = "allow"
non-ascii-literal = "allow"
partialeq-ne-impl = "allow"
similar-names = "allow"
single-match-else = "allow"
struct-excessive-bools = "allow"
use-self = "allow"
